export type LogoIconType =
  | 'binance'
  | 'bnb'
  | 'bsc'
  | 'coinbaseWallet'
  | 'ether'
  | 'metaMask'
  | 'trustWallet'
  | 'walletConnect'
  | 'planetarium'

export type ConnectorIconType =
  | 'coinbaseWallet'
  | 'metaMask'
  | 'trustWallet'
  | 'walletConnect'
  | 'binance'

export type IconSize = 16 | 24 | 32

export type IconType =
  | 'allowlist'
  | 'blockExplorer'
  | 'bscscan'
  | 'check'
  | 'calendar'
  | 'checkboxOff'
  | 'chevronDown'
  | 'chevronLeft'
  | 'chevronRight'
  | 'chevronUp'
  | 'chevronLine'
  | 'close'
  | 'coin'
  | 'coinStack'
  | 'edit'
  | 'copy'
  | 'discord'
  | 'docs'
  | 'done'
  | 'github'
  | 'globe'
  | 'hamburger'
  | 'info'
  | 'link'
  | 'lock'
  | 'mail'
  | 'medium'
  | 'mute'
  | 'outlink'
  | 'pause'
  | 'play'
  | 'refreshOn'
  | 'refreshOff'
  | 'secure'
  | 'slideClose'
  | 'star'
  | 'telegram'
  | 'time'
  | 'twitter'
  | 'transfer'
  | 'unlock'
  | 'unmute'
  | 'usd'
  | 'user'
  | 'warning'
