echo "NEXT_PUBLIC_INFURA_API_KEY=$NEXT_PUBLIC_INFURA_API_KEY" >> .env
echo "NEXT_PUBLIC_NODE_REAL_API_KEY=$NEXT_PUBLIC_NODE_REAL_API_KEY" >> .env
echo "NEXT_PUBLIC_GA_MEASUREMENT_ID=$NEXT_PUBLIC_GA_MEASUREMENT_ID" >> .env
echo "NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID=$NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID" >> .env

echo "NEXT_PUBLIC_BASE_URL=$NEXT_PUBLIC_BASE_URL" >> .env
echo "NEXT_PUBLIC_DOMAIN=$NEXT_PUBLIC_DOMAIN" >> .env
echo "NEXT_PUBLIC_IMGIX_HOSTNAME=$NEXT_PUBLIC_IMGIX_HOSTNAME" >> .env
echo "IMGIX_HOSTNAME=$IMGIX_HOSTNAME" >> .env

echo "NEXT_PUBLIC_AWS_BRANCH=$AWS_BRANCH" >> .env
echo "NEXT_PUBLIC_AWS_JOB_ID=$AWS_JOB_ID" >> .env
echo "NEXT_PUBLIC_AWS_JOB_ID=$AWS_JOB_ID" >> .env
echo "NEXT_PUBLIC_AWS_COMMIT_ID=$AWS_COMMIT_ID" >> .env
